### ISSUE TITLE
Plugin installation may fail due to expect_pods behavior

### ISSUE THREAD

**Issue by n549** [Netcracker/KubeMarine#107]
In some cases plugin installation fails due to expect_pods behavior.

Case 1.
For example, 2 ready pods have to be present to go further:
```
keycloak-0                 1/1     Running   0          100d
keycloak-postgresql-0      1/1     Running   0          100d
```
keycloak-postgresql-0 starts and becomes ready first and only then keycloak-0 starts and it requires some time to get ready.
If we define expect.pods as follows:
```
      - expect:
          pods:
            list:
              - keycloak-0
              - keycloak-postgresql-0
```
the job fails after timeout because of this condition never comes true:
https://github.com/Netcracker/KubeMarine/blob/f75f48a786a9c1f1c53affb7f6f7898e0f95cb63/kubemarine/plugins/__init__.py#L196

If we define expect_pods as follows:
```
      - expect:
          pods:
            list:
              - keycloak
              - keycloak-postgresql
```
there might be situation when keycloak-postgresql-0 is already Running and ready (1/1) but keycloak-0 is still not in Running state 
(in Init state, for example).
Then the plugin installation procedure will not wait for the keycloak-0 pod becomes ready and goes further:
https://github.com/Netcracker/KubeMarine/blob/f75f48a786a9c1f1c53affb7f6f7898e0f95cb63/kubemarine/plugins/__init__.py#L214-L220

Case 2. If there are pods with the same substring in the name in different namespaces, then expect.pods for this substring finishes when any of these pods is Running and ready. For example:
```
auth-system            keycloak-0                                        1/1     Running     0          101d
auth-system            keycloak-postgresql-0                             1/1     Running     0          101d
kubernetes-dashboard   keycloak-gatekeeper-87c5d87b9-fq5d7               1/1     Running     0          70d
```  
expect.pods for "keycloak" name finishes if keycloak-postgresql-0 or keycloak-gatekeeper-* is already Running and ready.  

Currently both such cases can be mitigated by adding 
```
        - shell:
            command: sleep 600
```
after expect.pods, so all the required pods manage to get ready, but it's rather not obviously.
