### ISSUE TITLE
Documentation installation-without-internet-resources is outdated

### ISSUE THREAD

**Issue by marniks7** [Netcracker/KubeMarine#231]
Hi,
during installation:
https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#installation-without-internet-resources

AR: got this error
ER: expect to see in documentation proper configuration
![image](https://user-images.githubusercontent.com/9289172/191830204-1325d50b-abfb-4fca-bbf4-ebf1ff34fcb8.png)

**Comment by koryaga** [comment]
@alku89  pls assess

**Comment by marniks7** [comment]
Hi @alku89,
i am trying to go further with installation without internet resources, 
here is part of my config
```yaml
services:
  kubeadm:
    kubernetesVersion: v1.22.2
    imageRepository: BBBB
  cri:
    containerdConfig:
      insecure-registries:
        - AAAA
      registry-mirrors:
        - YYYY
  thirdparties:
    /usr/bin/calicoctl:
      source: XXX/projectcalico/calicoctl/{{ plugins.calico.version }}/calicoctl-linux-amd64
    /usr/bin/kubeadm:
      source: XXX/kubernetes/kubeadm/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubeadm
    /usr/bin/kubelet:
      source: XXX/kubernetes/kubelet/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubelet
    /usr/bin/kubectl:
      source: XXX/kubernetes/kubectl/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubectl
```

but it tries to download kubelet from the internet and fails... what is wrong with my config?
![image](https://user-images.githubusercontent.com/9289172/193863657-08f57458-8ea7-408d-98bc-ca2b288f7d7c.png)

**Comment by marniks7** [comment]
```
node_defaults:
  keyfile: "/home/root/.ssh/my.key"
  username: "centos"
 
services:
  kubeadm:
    kubernetesVersion: v1.22.2
    imageRepository: example.company.com:port1
  cri:
    containerdConfig:
      insecure-registries:
        - example.company.com:port2
      registry-mirrors:
        - example.company.com:port3
  thirdparties:
    /usr/bin/calicoctl:
      source: XXX/projectcalico/calicoctl/{{ plugins.calico.version }}/calicoctl-linux-amd64
    /usr/bin/kubeadm:
      source: XXX/kubernetes/kubeadm/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubeadm
    /usr/bin/kubelet:
      source: XXX/kubernetes/kubelet/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubelet
    /usr/bin/kubectl:
      source: XXX/kubernetes/kubectl/{{ services.kubeadm.kubernetesVersion }}/bin/linux/amd64/kubectl

nodes:
  - name: "k8s-control-plane"
    address: "10.109.102.64"
    internal_address: "192.168.0.1"
    roles: ["control-plane", "worker"]

cluster_name: "10.109.102.64.nip.io"
```
