### ISSUE TITLE
Incorrect interface for vrrp IP if few vrrp IPs are specified with different interfaces

### ISSUE THREAD

**Issue by ilia1243** [Netcracker/KubeMarine#248]
TC: configure vrrp_ips section with few vrrp IPs and different interfaces, for example
```yaml
- interface: ens3
  ip: 192.168.2.5
- interface: ens4
  ip: 192.168.0.30
```
The enriched result will be
```yaml
- hosts: &id001
  - interface: ens3
    name: support-balancer-right-1
    priority: 254
  - interface: ens3
    name: support-balancer-right-2
    priority: 253
  id: 5a9ed0acb0
  interface: ens3
  ip: 192.168.2.5
  password: ee5e0d42
  router_id: '5'
- hosts: *id001
  id: e03c4ec807
  interface: ens4
  ip: 192.168.0.30
  password: 2b70fdd7
  router_id: '30'
```

RC: if `hosts` are not specified, Kubemarine [assigns](https://github.com/Netcracker/KubeMarine/blob/0.8.0/kubemarine/keepalived.py#L88) default list of hosts:
```yaml
inventory['vrrp_ips'][i]['hosts'] = default_names
```
which is later changed [in-place](https://github.com/Netcracker/KubeMarine/blob/0.8.0/kubemarine/keepalived.py#L92). Further vrrp IPs inherit changed `hosts` section with incorrect interface.

Solution: make copy of default_names.
```yaml
inventory['vrrp_ips'][i]['hosts'] = list(default_names)
```
