### ISSUE TITLE
Run tasks by node attributes specific parameters

### ISSUE THREAD

**Issue by alexarefev** [Netcracker/KubeMarine#419]
It's nice to have the functionality that allows to run tasks on particular nodes and nodes should be specified not by `name` but by their attributes eg. `labels` or `roles`. The following YAML describes the upgrade procedure:
```yaml
upgrade_plan:
  - v1.26.3
upgrade_nodes:
  labels: {region: infra}
```
The CLI usage:
kubemarine install --tasks="prepare.package_manager" --nodes="labels='region=infra'"
