### ISSUE TITLE
Differently processing inventory for public and env specific clusters

### ISSUE THREAD

**Issue by pranavcracker** [Netcracker/KubeMarine#465]
It has been observed that, the inventory is getting processed differently for the public clusters and env specific cluster.
Whereas the only difference between inventories for public clusters and env specific clusters should differ only in where thirdparties sources.

Currently difference observed as - 
**Public Cluster -**
```
cri:
    containerRuntime: containerd
    containerdConfig:
      plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc:
        runtime_type: io.containerd.runc.v2
      plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options:
        SystemdCgroup: 'true'
      version: 2 
```

**NC env cluster-**
```
cri:
    containerRuntime: containerd
    containerdConfig:
      plugins."io.containerd.grpc.v1.cri":
        sandbox_image: artifactorycn.netcracker.com:17115/pause:3.8
      plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc:
        runtime_type: io.containerd.runc.v2
      plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options:
        SystemdCgroup: 'true'
      plugins."io.containerd.grpc.v1.cri".registry.mirrors."artifactorycn.netcracker.com:17001":
        endpoint:
        - https://artifactorycn.netcracker.com:17001
      version: 2
```

**ER-** Final inventory should same apart from thirdparties source repositories.
