### ISSUE TITLE
Broken ingress-nginx after default all-in-one installation 

### ISSUE THREAD

**Issue by Imadzuma** [Netcracker/KubeMarine#496]
After merging PR https://github.com/Netcracker/KubeMarine/pull/479 default kubemarine configuration is not enough in case of all-in-one scheme without balancer.
For example for cluster.yaml:
```yaml
node_defaults:
  username: 'root'
  keyfile: '{{ env.NODE_KEY_FILE }}'
nodes:
  - name: node-all-in-one
    address: '192.168.56.102'
    internal_address: '192.168.56.102'
    roles:
      - control-plane
      - worker
cluster_name: test-local-k8s.com
```
Ingresses doesn't work for such configuration and all requests return `Connection reset by peer`, because of enabled proxy protocol, for example for dashboard:
```bash
root@node-all-in-one:~$ curl -v -k https://dashboard.test-local-k8s.com
*   Trying 192.168.56.102:443...
* Connected to dashboard.test-local-k8s.com (192.168.56.102) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to dashboard.test-local-k8s.com:443
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to dashboard.test-local-k8s.com:443
```

To solve that issue, it's needed to disable proxy protocol ic cluster.yaml, e.g.:
```yaml
node_defaults:
  username: 'root'
  keyfile: '{{ env.NODE_KEY_FILE }}'
nodes:
  - name: node-all-in-one
    address: '192.168.56.102'
    internal_address: '192.168.56.102'
    roles:
      - control-plane
      - worker
cluster_name: test-local-k8s.com

plugins:
  nginx-ingress-controller:
    config_map:
      use-proxy-protocol: "false"
```
But in fact, it's not clear from documentation. 

Additionally, we deploy such scheme in kubemarine [default integration tests](https://github.com/Netcracker/KubeMarine/blob/0.20.0/ci/default_cluster.yaml), but we don't check there, if ingresses  work. For future, we can add ingresses connectivity checks to `check_paas` or, (if it's not possible for some reason) as separate check in integration tests.
